---
language: java
jdk: openjdk17
dist: focal

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository

branches:
  only:
    - master
    - /support\/.*/
    - /fix/\.*/

stages:
  - name: tests
    if: commit_message !~ /\[skip tests\]/
  - name: release
    if: commit_message ~= /\[release\]/ AND branch ~= /^(master|support\/.+)$/ AND fork = false
  - name: publish
    if: commit_message ~= /\[publish\]/ AND branch ~= /^(master|support\/.+)$/ AND type != pull_request AND fork = false

before_install: bash _ci/init.sh

jobs:
  include:
    - name: "Unit Tests"
      stage: tests
      script: bash _ci/unit_tests.sh

    - name: "Source Clear Scan (SCA)"
      install: skip
      script: travis_wait 30 bash _ci/source_clear.sh

    - name: "Release"
      stage: release
      script: bash _ci/release.sh
      before_deploy: travis_retry source _ci/prepare_staging_deploy.sh
      deploy:
        provider: s3
        access_key_id: "${STAGING_AWS_ACCESS_KEY}"
        secret_access_key: "${STAGING_AWS_SECRET_KEY}"
        bucket: "alfresco-artefacts-staging"
        skip_cleanup: true
        region: "eu-west-1"
        local_dir: "deploy_dir"
        upload-dir: "enterprise/AlfrescoExtensionInspector/${VERSION}"
        on:
          all_branches: true

    - name: "Copy to S3 Release Bucket"
      stage: publish
      install: skip
      script: skip
      before_deploy: pip install awscli
      deploy:
        - provider: script
          script: sh _ci/copy_to_release_bucket.sh
          skip_cleanup: true
          on:
            all_branches: true
