---
language: java
jdk: openjdk11
dist: xenial


git:
  depth: false
  quiet: true


cache:
  directories:
    - ${HOME}/.m2/repository


branches:
  only:
    - master
    - /support\/.*/
    - /fix\/.*/
    - /feature\/.*/


stages:
  - build
  - release


jobs:
  include:
    - name: "Build + Tests"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/build.sh
    - name: "Source Clear Scan (SCA)"
    stage: build
    if: branch NOT IN (company_release)
    before_install: bash _ci/init.sh
    install: skip
    script: travis_wait 30 bash _ci/source_clear.sh

      - name: "Static Analysis (SAST)"
        if: branch = master AND type != pull_request
        stage: build
        before_install:
          - bash _ci/static_analysis_init.sh
          - bash _ci/init.sh
        script: bash _ci/static_analysis.sh

    - name: "WhiteSource"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/whitesource.sh

    - name: "Release"
      stage: release
      if: commit_message ~= /\[trigger release\]/ AND branch ~= /^(master|support\/.+)$/
      before_install: bash _ci/init.sh
      script: bash _ci/release.sh
