---
spring:
  main:
    banner_mode: "off"
  shell:
    interactive:
      enabled: false

inventory-report-resource-pattern: "classpath:bundled-inventories/*.json"

logging:
  level:
    root: warn
    org.alfresco.extension_inspector.inventory: info
