name: alfresco Extension Inspector Build Workflow

on:
  push:
    branches:
      - master
      - 'fix/**'
      - 'support/**'
      - 'feature/**'
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - 'fix/**'
      - 'support/**'
      - 'feature/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Typical Java workflow steps
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'maven'
      - name: Unit Tests
        run: _ci/unit_tests.sh
        shell: bash
      - name: Source Clear Scan (SCA)
        run: _ci/source_clear.sh
        shell: bash