name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      # Typical Java workflow steps
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'maven'