name: alfresco Extension Inspector Build Workflow

on:
  push:
    branches:
      - master
      - 'fix/**'
      - 'support/**'
      - 'feature/**'
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - 'fix/**'
      - 'support/**'
      - 'feature/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Typical Java workflow steps
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        env:
          JAVA_VERSION: 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

#      - name: Unit Tests
#        run: _ci/unit_tests.sh
#      - name: Source Clear Scan (SCA)
#        run: _ci/source_clear.sh