name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: test github action
        run: echo "Test Github Action for Alfresco Extension Inspector"